const wordData = {
    "One": ["wʌn", "一"],
    "Two": ["tuː", "二"],
    "Three": ["θriː", "三"],
    "Four": ["fɔː", "四"],
    "Five": ["faɪv", "五"],
    "Six": ["sɪks", "六"],
    "Seven": ["ˈsevn", "七"],
    "Eight": ["eɪt", "八"],
    "Nine": ["naɪn", "九"],
    "Ten": ["ten", "十"],
    "Eleven": ["ɪˈlevn", "十一"],
    "Twelve": ["twelv", "十二"],
    "Thirteen": ["ˌθɜːˈtiːn", "十三"],
    "Fourteen": ["ˌfɔːˈtiːn", "十四"],
    "Fifteen": ["ˌfɪfˈtiːn", "十五"],
    "Sixteen": ["ˌsɪksˈtiːn", "十六"],
    "Seventeen": ["ˌsevnˈtiːn", "十七"],
    "Eighteen": ["ˌeɪˈtiːn", "十八"],
    "Nineteen": ["ˌnaɪnˈtiːn", "十九"],
    "Twenty": ["ˈtwenti", "二十"]
}; 