const wordData_250114 = {
    'difficult': ['/ˈdɪfɪkəlt/', '困难的'],
    'closet': ['/ˈklɒzɪt/', '橱柜'],
    'fast': ['/fɑːst/', '迅速的'],
    'poster': ['/ˈpəʊstə(r)/', '海报'],
    'down': ['/daʊn/', '向下'],
    'dry': ['/draɪ/', '干的'],
    'except': ['/ɪkˈsept/', '除...之外'],
    'earring': ['/ˈɪərɪŋ/', '耳饰'],
    'article': ['/ˈɑːtɪkl/', '文章'],
    'skirt': ['/skɜːt/', '裙子'],
    'husband': ['/ˈhʌzbənd/', '丈夫'],
    'sit': ['/sɪt/', '坐'],
    'stamp': ['/stæmp/', '邮票'],
    'exit': ['/ˈeksɪt/', '出口'],
    'cereal': ['/ˈsɪəriəl/', '谷物'],
    'available': ['/əˈveɪləbl/', '可用的，有空的'],
    'calendar': ['/ˈkælɪndə(r)/', '日历'],
    'discuss': ['/dɪˈskʌs/', '讨论'],
    'advert': ['/ˈædvɜːt/', '广告，注意'],
    'secretary': ['/ˈsekrətri/', '秘书'],
    'bin': ['/bɪn/', '垃圾桶'],
    'file': ['/faɪl/', '文件'],
    'list': ['/lɪst/', '目录'],
    'uniform': ['/ˈjuːnɪfɔːm/', '制服'],
    'tram': ['/træm/', '有轨电车'],
    'improve': ['/ɪmˈpruːv/', '改善'],
    'outside': ['/ˌaʊtˈsaɪd/', '在户外'],
    'tie': ['/taɪ/', '领带'],
    'pain': ['/peɪn/', '痛'],
    'nationality': ['/ˌnæʃəˈnæləti/', '国籍'],
    'polite': ['/pəˈlaɪt/', '有礼貌的'],
    'check': ['/tʃek/', '检查'],
    'foreign': ['/ˈfɒrən/', '外国的'],
    'call': ['/kɔːl/', '打电话'],
    'cricket': ['/ˈkrɪkɪt/', '板球'],
    'few': ['/fjuː/', '很少的'],
    'rest': ['/rest/', '休息'],
    'however': ['/haʊˈevə(r)/', '然而']
};
const wordData_250115 = {
    'dot': ['/dɒt/', '圆点'],
    'guy': ['/ɡaɪ/', '男人'],
    'folder': ['/ˈfəʊldə(r)/', '文件夹'],
    'chef': ['/ʃef/', '主厨'],
    'transport': ['/ˈtrænspɔːt/', '交通工具'],
    'melon': ['/ˈmelən/', '甜瓜'],
    'discount': ['/ˈdɪskaʊnt/', '折扣'],
    'occupation': ['/ˌɒkjuˈpeɪʃn/', '占领'],
    'visit': ['/ˈvɪzɪt/', '拜访'],
    'meet': ['/miːt/', '见面，相遇'],
    'musical': ['/ˈmjuːzɪkl/', '音乐的'],
    'mushroom': ['/ˈmʌʃrʊm/', '蘑菇'],
    'bit': ['/bɪt/', '少量'],
    'plane': ['/pleɪn/', '飞机'],
    'receipt': ['/rɪˈsiːt/', '收据'],
    'entrance': ['/ˈentrəns/', '入口'],
    'contact': ['/ˈkɒntækt/', '联系']
};
const wordData_250116 = {
    'normal': ['/ˈnɔːml/', '正常的'],
    'usually': ['/ˈjuːʒuəli/', '通常'],
    'boat': ['/bəʊt/', '小船'],
    'congratulation': ['/kənˌɡrætʃuˈleɪʃn/', '祝贺'],
    'rock': ['/rɒk/', '岩石'],
    'hard': ['/hɑːd/', '困难的，坚硬的'],
    'fridge': ['/frɪdʒ/', '冰箱'],
    'move': ['/muːv/', '移动'],
    'department': ['/dɪˈpɑːtmənt/', '部门'],
    'wait': ['/weɪt/', '等待'],
    'learn': ['/lɜːn/', '学习'],
    'itself': ['/ɪtˈself/', '它自己']
};
const wordData_250117 = {
    'cartoon': ['/kɑːˈtuːn/', '动画片'],
    'suitcase': ['/ˈsuːtkeɪs/', '手提箱'],
    'hold': ['/həʊld/', '掌握'],
    'thing': ['/θɪŋ/', '东西'],
    'spend': ['/spend/', '花费'],
    'son': ['/sʌn/', '儿子'],
    'rubber': ['/ˈrʌbə(r)/', '橡皮'],
    'once': ['/wʌns/', '一次，曾经'],
    'month': ['/mʌnθ/', '月'],
    'kind': ['/kaɪnd/', '种类'],
    'guest': ['/ɡest/', '客人'],
    'else': ['/els/', '其他的'],
    'appointment': ['/əˈpɔɪntmənt/', '预约'],
    'front': ['/frʌnt/', '前面的'],
    'chain': ['/tʃeɪn/', '链条，束缚']
};
const wordData_250118 = {
    'finger': ['/ˈfɪŋɡə(r)/', '手指'],
    'guide': ['/ɡaɪd/', '导游'],
    'town': ['/taʊn/', '城镇'],
    'people': ['/ˈpiːpl/', '人'],
    'bank': ['/bæŋk/', '银行'],
    'playground': ['/ˈpleɪɡraʊnd/', '操场'],
    'snack': ['/snæk/', '零食'],
    'same': ['/seɪm/', '相同的'],
    'pound': ['/paʊnd/', '英镑'],
    'look': ['/lʊk/', '看'],
    'mouth': ['/maʊθ/', '嘴'],
    'map': ['/mæp/', '地图'],
    'top': ['/tɒp/', '顶部'],
    'early': ['/ˈɜːli/', '早期的'],
    'kilometre': ['/ˈkɪləmiːtə(r)/', '千米']
};
const wordData_250119 = {
    'village': ['/ˈvɪlɪdʒ/', '村庄'],
    'salad': ['/ˈsæləd/', '色拉'],
    'university': ['/ˌjuːnɪˈvɜːsəti/', '大学'],
    'cash': ['/kæʃ/', '现金'],
    'serve': ['/sɜːv/', '服务'],
    'tablet': ['/ˈtæblət/', '药片'],
    'ago': ['/əˈɡəʊ/', '以前'],
    'clock': ['/klɒk/', '钟'],
    'local': ['/ˈləʊkl/', '当地的'],
    'together': ['/təˈɡeðə(r)/', '一起'],
    'alone': ['/əˈləʊn/', '单独的'],
    'beginning': ['/bɪˈɡɪnɪŋ/', '开始'],
    'upset': ['/ʌpˈset/', '沮丧的'],
    'event': ['/ɪˈvent/', '事件'],
    'last': ['/lɑːst/', '上一个，最后的']
};
const wordData_250120 = {
    'bad': ['/bæd/', '坏的'],
    'suggest': ['/səˈdʒest/', '建议'],
    'date': ['/deɪt/', '日期'],
    'remember': ['/rɪˈmembə(r)/', '记得'],
    'better': ['/ˈbetə(r)/', '更好的'],
    'little': ['/ˈlɪtl/', '小的'],
    'crowd': ['/kraʊd/', '人群'],
    'lesson': ['/ˈlesn/', '课程'],
    'box': ['/bɒks/', '盒子'],
    'wallet': ['/ˈwɒlɪt/', '钱包'],
    'chemist': ['/ˈkemɪst/', '化学家'],
    'myself': ['/maɪˈself/', '自己'],
    'identification': ['/aɪˌdentɪfɪˈkeɪʃn/', '辨认'],
    'sausage': ['/ˈsɒsɪdʒ/', '香肠'],
    'usual': ['/ˈjuːʒuəl/', '通常的']
};
const wordData_250121 = {
    'pleasant': ['/ˈpleznt/', '舒适的'],
    'digital': ['/ˈdɪdʒɪtl/', '数码的'],
    'dictionary': ['/ˈdɪkʃənri/', '字典'],
    'adult': ['/ˈædʌlt/', '成年人'],
    'news': ['/njuːz/', '新闻'],
    'where': ['/weə(r)/', '哪里'],
    'person': ['/ˈpɜːsn/', '本人'],
    'catch': ['/kætʃ/', '接住'],
    'enjoy': ['/ɪnˈdʒɔɪ/', '享受'],
    'electricity': ['/ɪˌlekˈtrɪsəti/', '电'],
    'musician': ['/mjuːˈzɪʃn/', '音乐家'],
    'shop': ['/ʃɒp/', '商店'],
    'much': ['/mʌtʃ/', '非常'],
    'science': ['/ˈsaɪəns/', '科学'],
    'cent': ['/sent/', '分币']
};
const wordData_250122 = {
    'carry': ['/ˈkæri/', '携带'],
    'park': ['/pɑːk/', '公园'],
    'carpet': ['/ˈkɑːpɪt/', '地毯'],
    'yourself': ['/jɔːˈself/', '你自己'],
    'talk': ['/tɔːk/', '讲话'],
    'traffic': ['/ˈtræfɪk/', '交通'],
    'lorry': ['/ˈlɒri/', '卡车'],
    'drawing': ['/ˈdrɔːɪŋ/', '画画'],
    'mile': ['/maɪl/', '英里'],
    'fan': ['/fæn/', '风扇，球迷，歌迷'],
    'radio': ['/ˈreɪdiəʊ/', '收音机'],
    'spoon': ['/spuːn/', '匙'],
    'luggage': ['/ˈlʌɡɪdʒ/', '行李'],
    'tomorrow': ['/təˈmɒrəʊ/', '明天'],
    'elevator': ['/ˈelɪveɪtə(r)/', '电梯']
};
const wordData_250123 = {
    'weekly': ['/ˈwiːkli/', '每周的，周报'],
    'open': ['/ˈəʊpən/', '打开'],
    'tour': ['/tʊə(r)/', '旅游'],
    'blanket': ['/ˈblæŋkɪt/', '毛毯'],
    'aeroplane': ['/ˈeərəpleɪn/', '飞机'],
    'enter': ['/ˈentə(r)/', '进入'],
    'fit': ['/fɪt/', '适合'],
    'spare': ['/speə(r)/', '备用的'],
    'tent': ['/tent/', '帐篷'],
    'yet': ['/jet/', '仍然'],
    'lake': ['/leɪk/', '湖泊'],
    'headache': ['/ˈhedeɪk/', '头痛'],
    'butter': ['/ˈbʌtə(r)/', '黄油'],
    'skate': ['/skeɪt/', '滑冰'],
    'sweater': ['/ˈswetə(r)/', '毛衣']
};
const wordData_250125 = {
    'popular': ['/ˈpɒpjələ(r)/', '受欢迎的'],
    'already': ['/ɔːlˈredi/', '已经'],
    'wild': ['/waɪld/', '野性的'],
    'sell': ['/sel/', '卖'],
    'some': ['/sʌm/', '一些'],
    'cool': ['/kuːl/', '凉爽的，从容的'],
    'street': ['/striːt/', '街道'],
    'concert': ['/ˈkɒnsət/', '音乐会'],
    'with': ['/wɪð/', '和，用'],
    'deep': ['/diːp/', '深的'],
    'baseball': ['/ˈbeɪsbɔːl/', '棒球'],
    'information': ['/ˌɪnfəˈmeɪʃn/', '信息'],
    'strawberry': ['/ˈstrɔːbəri/', '草莓'],
    'real': ['/rɪəl/', '真的'],
    'butterfly': ['/ˈbʌtəflaɪ/', '蝴蝶']
};
const wordData = Object.assign(wordData_250114, wordData_250115, wordData_250116, 
    wordData_250117, wordData_250118, wordData_250119, wordData_250120, wordData_250121, 
    wordData_250122, wordData_250123, wordData_250125);

const wordData_error = {
    'secretary': ['/ˈsekrətri/', '秘书'],
    'cricket': ['/ˈkrɪkɪt/', '板球'],
    'occupation': ['/ˌɒkjuˈpeɪʃn/', '占领'],
    'receipt': ['/rɪˈsiːt/', '收据'],
    'congratulation': ['/kənˌɡrætʃuˈleɪʃn/', '祝贺'],
    'department': ['/dɪˈpɑːtmənt/', '部门'],
    'normal': ['/ˈnɔːml/', '正常的'],
    'appointment': ['/əˈpɔɪntmənt/', '预约'],
    'guide': ['/ɡaɪd/', '导游'],
    'snack': ['/snæk/', '零食'],
    'pound': ['/paʊnd/', '英镑'],
    'kilometre': ['/ˈkɪləmiːtə(r)/', '千米'],
    'last': ['/lɑːst/', '上一个，最后的'],
    'event': ['/ɪˈvent/', '事件'],
    'village': ['/ˈvɪlɪdʒ/', '村庄'],
    'university': ['/ˌjuːnɪˈvɜːsəti/', '大学'],
    'suggest': ['/səˈdʒest/', '建议'],
    'wallet': ['/ˈwɒlɪt/', '钱包'],
    'chemist': ['/ˈkemɪst/', '化学家'],
    'luggage': ['/ˈlʌɡɪdʒ/', '行李']
};