const wordData = {
    'divine': ['/dɪˈvaɪn/', '神的'],
    'the god of the Divine Farmer': ['/ðə ɡɒd ɒv ðə dɪˈvaɪn ˈfɑːmə/', '神农帝'],
    'farm': ['/fɑːm/', '种田'],
    'because of': ['/bɪˈkɒz ɒv/', '由于'],
    'survive': ['/səˈvaɪv/', '生存'],
    'starvation': ['/stɑːˈveɪʃn/', '饥饿'],
    'gradually': ['/ˈɡrædʒuəli/', '逐渐地'],
    'develop': ['/dɪˈveləp/', '发展'],
    'agriculture': ['/ˈæɡrɪkʌltʃə/', '农业'],
    'even though': ['/ˈiːvn ðəʊ/', '即使'],
    'no longer': ['/nəʊ ˈlɒŋɡə/', '不再'],
    'in short supply': ['/ɪn ʃɔːt səˈplaɪ/', '供应不足'],
    'receive': ['/rɪˈsiːv/', '收到'],
    'medical': ['/ˈmedɪkl/', '医学的'],
    'treatment': ['/ˈtriːtmənt/', '治疗'],
    'medication': ['/ˌmedɪˈkeɪʃn/', '药物'],
    'scarce': ['/skeəs/', '缺乏的'],
    'be worried about': ['/bi ˈwʌrid əˈbaʊt/', '担心'],
    'believe': ['/bɪˈliːv/', '相信'],
    'sorcery': ['/ˈsɔːsəri/', '魔术，巫术'],
    'be able to': ['/bi ˈeɪbl tuː/', '能够'],
    'practice medicine': ['/ˈpræktɪs ˈmedɪsn/', '从事医学实践'],
    'pass by': ['/pɑːs baɪ/', '走过'],
    'province': ['/ˈprɒvɪns/', '省份'],
    'varieties of': ['/vəˈraɪətiz ɒv/', '各种各样的'],
    'herbs': ['/hɜːbz/', '药草'],
    'realize': ['/ˈrɪəlaɪz/', '意识到'],
    'serve as': ['/sɜːv æz/', '对~起作用'],
    'medicinal': ['/məˈdɪsɪnl/', '药用的；有疗效的'],
    'value': ['/ˈvæljuː/', '价值'],
    'effort': ['/ˈefət/', '努力'],
    'a variety of': ['/ə vəˈraɪəti ɒv/', '各种各样的'],
    'routinely': ['/ruːˈtiːnli/', '毫无意外地'],
    'health care': ['/helθ keə/', '健康治疗'],
    'knowledge': ['/ˈnɒlɪdʒ/', '知识'],
    'was handed down': ['/wɒz ˈhændɪd daʊn/', '传承下来的'],
    'oral tradition': ['/ˈɔːrəl trəˈdɪʃn/', '口头传统'],
    'centuries': ['/ˈsentʃəriz/', '世纪'],
    'in a formal manner': ['/ɪn ə ˈfɔːml ˈmænə/', '用正常的方式'],
    'was named after': ['/wɒz neɪmd ˈɑːftə/', '以~命名'],
    'known as': ['/nəʊn æz/', '被认为是']
}; 