const wordData = {
    'divine': ['/dɪˈvaɪn/', '神的'],
    'farm': ['/fɑːm/', '种田'],
    'survive': ['/səˈvaɪv/', '生存'],
    'starvation': ['/stɑːˈveɪʃn/', '饥饿'],
    'gradually': ['/ˈɡrædʒuəli/', '逐渐地'],
    'develop': ['/dɪˈveləp/', '发展'],
    'agriculture': ['/ˈæɡrɪkʌltʃə/', '农业'],
    'receive': ['/rɪˈsiːv/', '收到'],
    'medical': ['/ˈmedɪkl/', '医学的'],
    'treatment': ['/ˈtriːtmənt/', '治疗'],
    'medication': ['/ˌmedɪˈkeɪʃn/', '药物'],
    'scarce': ['/skeəs/', '缺乏的'],
    'believe': ['/bɪˈliːv/', '相信'],
    'sorcery': ['/ˈsɔːsəri/', '魔术，巫术'],
    'pass by': ['/pɑːs baɪ/', '走过'],
    'province': ['/ˈprɒvɪns/', '省份'],
    'herbs': ['/hɜːbz/', '药草'],
    'realize': ['/ˈrɪəlaɪz/', '意识到'],
    'medicinal': ['/məˈdɪsɪnl/', '药用的；有疗效的'],
    'value': ['/ˈvæljuː/', '价值'],
    'effort': ['/ˈefət/', '努力'],
    'routinely': ['/ruːˈtiːnli/', '毫无意外地'],
    'knowledge': ['/ˈnɒlɪdʒ/', '知识'],
    'centuries': ['/ˈsentʃəriz/', '世纪'],
}; 