const wordData_250114 = {
    'difficult': ['/ˈdɪfɪkəlt/', '困难的'],
    'closet': ['/ˈklɒzɪt/', '橱柜'],
    'fast': ['/fɑːst/', '迅速的'],
    'poster': ['/ˈpəʊstə(r)/', '海报'],
    'down': ['/daʊn/', '向下'],
    'dry': ['/draɪ/', '干的'],
    'except': ['/ɪkˈsept/', '除...之外'],
    'earring': ['/ˈɪərɪŋ/', '耳饰'],
    'article': ['/ˈɑːtɪkl/', '文章'],
    'skirt': ['/skɜːt/', '裙子'],
    'husband': ['/ˈhʌzbənd/', '丈夫'],
    'sit': ['/sɪt/', '坐'],
    'stamp': ['/stæmp/', '邮票'],
    'exit': ['/ˈeksɪt/', '出口'],
    'cereal': ['/ˈsɪəriəl/', '谷物'],
    'available': ['/əˈveɪləbl/', '可用的，有空的'],
    'calendar': ['/ˈkælɪndə(r)/', '日历'],
    'discuss': ['/dɪˈskʌs/', '讨论'],
    'advert': ['/ˈædvɜːt/', '广告，注意'],
    'secretary': ['/ˈsekrətri/', '秘书'],
    'bin': ['/bɪn/', '垃圾桶'],
    'file': ['/faɪl/', '文件'],
    'list': ['/lɪst/', '目录'],
    'uniform': ['/ˈjuːnɪfɔːm/', '制服'],
    'tram': ['/træm/', '有轨电车'],
    'improve': ['/ɪmˈpruːv/', '改善'],
    'outside': ['/ˌaʊtˈsaɪd/', '在户外'],
    'tie': ['/taɪ/', '领带'],
    'pain': ['/peɪn/', '痛'],
    'nationality': ['/ˌnæʃəˈnæləti/', '国籍'],
    'polite': ['/pəˈlaɪt/', '有礼貌的'],
    'check': ['/tʃek/', '检查'],
    'foreign': ['/ˈfɒrən/', '外国的'],
    'call': ['/kɔːl/', '打电话'],
    'cricket': ['/ˈkrɪkɪt/', '板球'],
    'few': ['/fjuː/', '很少的'],
    'rest': ['/rest/', '休息'],
    'however': ['/haʊˈevə(r)/', '然而']
};
const wordData_250115 = {
    'dot': ['/dɒt/', '圆点'],
    'guy': ['/ɡaɪ/', '男人'],
    'folder': ['/ˈfəʊldə(r)/', '文件夹'],
    'chef': ['/ʃef/', '主厨'],
    'transport': ['/ˈtrænspɔːt/', '交通工具'],
    'melon': ['/ˈmelən/', '甜瓜'],
    'discount': ['/ˈdɪskaʊnt/', '折扣'],
    'occupation': ['/ˌɒkjuˈpeɪʃn/', '占领'],
    'visit': ['/ˈvɪzɪt/', '拜访'],
    'meet': ['/miːt/', '见面，相遇'],
    'musical': ['/ˈmjuːzɪkl/', '音乐的'],
    'mushroom': ['/ˈmʌʃrʊm/', '蘑菇'],
    'bit': ['/bɪt/', '少量'],
    'plane': ['/pleɪn/', '飞机'],
    'receipt': ['/rɪˈsiːt/', '收据'],
    'entrance': ['/ˈentrəns/', '入口'],
    'contact': ['/ˈkɒntækt/', '联系']
};
const wordData_250116 = {
    'normal': ['/ˈnɔːml/', '正常的'],
    'usually': ['/ˈjuːʒuəli/', '通常'],
    'boat': ['/bəʊt/', '小船'],
    'congratulation': ['/kənˌɡrætʃuˈleɪʃn/', '祝贺'],
    'rock': ['/rɒk/', '岩石'],
    'hard': ['/hɑːd/', '困难的，坚硬的'],
    'fridge': ['/frɪdʒ/', '冰箱'],
    'move': ['/muːv/', '移动'],
    'department': ['/dɪˈpɑːtmənt/', '部门'],
    'wait': ['/weɪt/', '等待'],
    'learn': ['/lɜːn/', '学习'],
    'itself': ['/ɪtˈself/', '它自己']
};
const wordData_250117 = {
    'cartoon': ['/kɑːˈtuːn/', '动画片'],
    'suitcase': ['/ˈsuːtkeɪs/', '手提箱'],
    'hold': ['/həʊld/', '掌握'],
    'thing': ['/θɪŋ/', '东西'],
    'spend': ['/spend/', '花费'],
    'son': ['/sʌn/', '儿子'],
    'rubber': ['/ˈrʌbə(r)/', '橡皮'],
    'once': ['/wʌns/', '一次，曾经'],
    'month': ['/mʌnθ/', '月'],
    'kind': ['/kaɪnd/', '种类'],
    'guest': ['/ɡest/', '客人'],
    'else': ['/els/', '其他的'],
    'appointment': ['/əˈpɔɪntmənt/', '预约'],
    'front': ['/frʌnt/', '前面的'],
    'chain': ['/tʃeɪn/', '链条，束缚']
};
const wordData_250118 = {
    'finger': ['/ˈfɪŋɡə(r)/', '手指'],
    'guide': ['/ɡaɪd/', '导游'],
    'town': ['/taʊn/', '城镇'],
    'people': ['/ˈpiːpl/', '人'],
    'bank': ['/bæŋk/', '银行'],
    'playground': ['/ˈpleɪɡraʊnd/', '操场'],
    'snack': ['/snæk/', '零食'],
    'same': ['/seɪm/', '相同的'],
    'pound': ['/paʊnd/', '英镑'],
    'look': ['/lʊk/', '看'],
    'mouth': ['/maʊθ/', '嘴'],
    'map': ['/mæp/', '地图'],
    'top': ['/tɒp/', '顶部'],
    'early': ['/ˈɜːli/', '早期的'],
    'kilometre': ['/ˈkɪləmiːtə(r)/', '千米']
};
const wordData_250119 = {
    'village': ['/ˈvɪlɪdʒ/', '村庄'],
    'salad': ['/ˈsæləd/', '色拉'],
    'university': ['/ˌjuːnɪˈvɜːsəti/', '大学'],
    'cash': ['/kæʃ/', '现金'],
    'serve': ['/sɜːv/', '服务'],
    'tablet': ['/ˈtæblət/', '药片'],
    'ago': ['/əˈɡəʊ/', '以前'],
    'clock': ['/klɒk/', '钟'],
    'local': ['/ˈləʊkl/', '当地的'],
    'together': ['/təˈɡeðə(r)/', '一起'],
    'alone': ['/əˈləʊn/', '单独的'],
    'beginning': ['/bɪˈɡɪnɪŋ/', '开始'],
    'upset': ['/ʌpˈset/', '沮丧的'],
    'event': ['/ɪˈvent/', '事件'],
    'last': ['/lɑːst/', '上一个，最后的']
};
const wordData = Object.assign(wordData_250114, wordData_250115, wordData_250116, 
    wordData_250117, wordData_250118, wordData_250119);

const wordData_error = {
    'secretary': ['/ˈsekrətri/', '秘书'],
    'cricket': ['/ˈkrɪkɪt/', '板球'],
    'occupation': ['/ˌɒkjuˈpeɪʃn/', '占领'],
    'receipt': ['/rɪˈsiːt/', '收据'],
    'congratulation': ['/kənˌɡrætʃuˈleɪʃn/', '祝贺'],
    'department': ['/dɪˈpɑːtmənt/', '部门'],
    'normal': ['/ˈnɔːml/', '正常的'],
    'appointment': ['/əˈpɔɪntmənt/', '预约'],
    'guide': ['/ɡaɪd/', '导游'],
    'snack': ['/snæk/', '零食'],
    'pound': ['/paʊnd/', '英镑'],
    'kilometre': ['/ˈkɪləmiːtə(r)/', '千米'],
    'last': ['/lɑːst/', '上一个，最后的'],
    'event': ['/ɪˈvent/', '事件'],
    'village': ['/ˈvɪlɪdʒ/', '村庄'],
    'university': ['/ˌjuːnɪˈvɜːsəti/', '大学']
};